// Generates src/generated/contract.ts from the contract artifact
// (contract/sdk-contract.json): the version, the constants, the error
// catalog and every interaction's request, reply, item and trailer types.
// Design 12 § the artifact: an SDK generates these from the artifact and
// nothing else; behavior is written by hand. Run `npm run generate`; CI
// fails when the committed file differs from a fresh generation.
import { readFileSync, writeFileSync } from "node:fs";
import { compile } from "json-schema-to-typescript";
import prettier from "prettier";

const contract = JSON.parse(readFileSync("contract/sdk-contract.json", "utf8"));

const pascal = (s) =>
  s
    .split(/[.\-_]/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const out = [];
out.push("// Code generated by scripts/generate.mjs from contract/sdk-contract.json. DO NOT EDIT.");
out.push("/* eslint-disable */");
out.push("");
out.push(`/** The contract version this SDK implements (design 12 § the artifact). */`);
out.push(`export const CONTRACT_VERSION = ${JSON.stringify(contract.version)};`);
out.push("");

const constant = (name, doc, value) => {
  out.push(`/** ${doc} */`);
  out.push(`export const ${name} = ${JSON.stringify(value, null, 2)} as const;`);
  out.push("");
};
constant("SHAPES", "The interaction shapes the contract describes.", contract.shapes);
constant("HEADERS", "The headers the wire speaks.", contract.headers);
constant("GRAMMARS", "Name grammars, derivations, META keys and vocabularies.", contract.grammars);
constant("STREAM_SETTINGS", "Settings every log stream carries.", contract.streamSettings);
constant("CLIENT_DEFAULTS", "The defaults a client applies.", contract.clientDefaults);
constant("FOLD", "The fold step's decisions and rules.", contract.fold);

const codes = contract.errors.map((e) => e.code);
out.push("/** The error catalog: every code a service returns, with its meaning. */");
out.push(`export const ERROR_CATALOG = ${JSON.stringify(contract.errors, null, 2)} as const;`);
out.push("");
out.push("/** A code from the error catalog. */");
out.push(`export type ErrorCode = ${codes.map((c) => JSON.stringify(c)).join(" | ")};`);
out.push("");
out.push("/** The fold step's decisions. */");
out.push(`export type FoldDecision = ${contract.fold.decisions.map((d) => JSON.stringify(d)).join(" | ")};`);
out.push("");

const opts = { bannerComment: "", strictIndexSignatures: true, unknownAny: true, format: false };

// A schema that constrains nothing is "any JSON" in the contract; the
// compiler would read it as an object, so it is marked unknown.
const shaping = ["type", "enum", "const", "$ref", "anyOf", "oneOf", "allOf", "properties", "items"];
const anyJSON = (schema) => {
  if (Array.isArray(schema)) return schema.map(anyJSON);
  if (typeof schema !== "object" || schema === null) return schema;
  const out = Object.fromEntries(Object.entries(schema).map(([k, v]) => [k, anyJSON(v)]));
  if (out.properties) {
    for (const [k, v] of Object.entries(out.properties)) {
      if (typeof v === "object" && v !== null && !shaping.some((key) => key in v)) {
        out.properties[k] = { ...v, tsType: "unknown" };
      }
    }
  }
  return out;
};
for (const [name, schema] of Object.entries(contract.records)) {
  out.push(await compile(anyJSON(schema), pascal(name) + "Record", opts));
}
const subjects = {};
for (const it of contract.interactions) {
  const base = pascal(it.name);
  for (const part of ["request", "reply", "item", "trailer"]) {
    const schema = it[part];
    if (schema && schema.type) {
      out.push(await compile(anyJSON(schema), base + pascal(part), opts));
    }
  }
  if (it.subject) {
    subjects[it.name] = it.subject;
  }
}
constant(
  "SUBJECTS",
  "Every interaction's subject; <log>, <index> and <thing> are filled at the call.",
  subjects,
);
out.push(
  `/** Every interaction's shape. */\nexport const INTERACTION_SHAPES = ${JSON.stringify(
    Object.fromEntries(contract.interactions.map((it) => [it.name, it.shape])),
    null,
    2,
  )} as const;\n`,
);

const config = await prettier.resolveConfig("src/generated/contract.ts");
const text = await prettier.format(out.join("\n"), { ...config, parser: "typescript" });
writeFileSync("src/generated/contract.ts", text);
console.log("src/generated/contract.ts written");
